services:
  nexotv:
    build: .
#    image: savibrabo/nexotv:latest
    container_name: nexotv
#    networks:
#      - npm-net
#    ports:
#      - "7000:7000"
    network_mode: service:protonvpn
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    depends_on:
      - protonvpn
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:7000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
